- id: adjust_lamp_dimmer_based_on_vivarium_temp
  alias: "Adjust Lamp Dimmer Based on Vivarium Temp"
  trigger:
    - platform: state
      entity_id: sensor.esphome_web_e86508_vivarium_temperature
  action:
    - variables:
        temp: "{{ states('sensor.esphome_web_e86508_vivarium_temperature') | float }}"
        percent: >-
          {% if temp < 22 %}
            100
          {% elif temp > 29 %}
            0
          {% elif temp >= 27 %}
            {{ 50 - ((temp - 27) * (50 / 2)) | round(0) }}
          {% elif temp >= 22 %}
            {{ 100 - ((temp - 22) * (50 / 5)) | round(0) }}
          {% else %}
            100
          {% endif %}
    - service: light.turn_on
      target:
        entity_id: light.wifi_plug_dimmer
      data:
        brightness_pct: "{{ percent }}"
    - service: input_number.set_value
      target:
        entity_id: input_number.vivarium_dimmer_percent
      data:
        value: "{{ percent }}"