esphome:
  name: vivsensor320
  friendly_name: VivariumII
  min_version: 2025.5.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_size: 16MB

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "6b/aM1kv5AO7QxCHrUNSwmBTTMHqumrld3cIjFkHsgg="

ota:
  - platform: esphome
    password: "45729663d51cd36a476d62ffa87f19ff"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Viv3 Fallback Hotspot"
    password: "FqYYZgJOn9Mg"

captive_portal:

spi:
  clk_pin: GPIO39
  mosi_pin: GPIO38
  
sensor:
  - platform: homeassistant
    id: dimmer_percent
    entity_id: input_number.vivarium_dimmer_percent
  - platform: homeassistant
    id: ext_temp
    entity_id: sensor.esphome_web_e86508_vivarium_temperature
  - platform: homeassistant
    id: ext_hum
    entity_id: sensor.esphome_web_e86508_vivarium_humidity

display:
  - platform: st7789v
    id: my_display
    model: CUSTOM
    width: 240
    height: 320
    offset_height: 0
    offset_width: 0
    cs_pin: 45
    dc_pin: 42
    reset_pin: 0
    backlight_pin: 1
    rotation: 270
    lambda: |-
      it.printf(14, 10, id(Roboto), Color(255, 255, 255), "VIVARIUM");
      it.printf(14, 45, id(Roboto_14), Color(255, 255, 255), "BASKING");
      it.printf(14, 100, id(Roboto_14), Color(255, 255, 255), "CENTRAL");
      it.printf(14, 156, id(Roboto_14), Color(255, 255, 255), "LOWER");
      it.printf(115, 45, id(Roboto_14), Color(255, 255, 255), "HUMIDITY");
      it.printf(115, 100, id(Roboto_14), Color(255, 255, 255), "HEAT");
      it.printf(115, 156, id(Roboto_14), Color(255, 255, 255), "UV");

      it.printf(74, 64, id(Roboto_14), Color(255, 255, 255), "°C");
      it.printf(74, 122, id(Roboto_14), Color(255, 255, 255), "°C");
      it.printf(74, 180, id(Roboto_14), Color(255, 255, 255), "°C");
      it.printf(175, 64, id(Roboto_14), Color(255, 255, 255), "%%");
      it.printf(175, 122, id(Roboto_14), Color(255, 255, 255), "%%");

      it.printf(14, 60, id(Roboto_30), Color(76, 175, 80), "%.1f", id(ext_temp).state);
      it.printf(14, 117, id(Roboto_30), Color(255, 130, 0), "25.1");
      it.printf(14, 175, id(Roboto_30), Color(233, 30, 99), "25.1");

      it.printf(115, 60, id(Roboto_30), Color(255, 130, 0), "%.1f", id(ext_hum).state);
      it.printf(115, 117, id(Roboto_30), Color(76, 175, 80), "%.0f", id(dimmer_percent).state);
      it.printf(115, 175, id(Roboto_30), Color(76, 175, 80), "3.1");
      
      it.filled_circle(245, 88, 37, Color(238, 238, 238));
      it.filled_circle(265, 72, 32, Color(0, 0, 0));
      it.filled_circle(227, 102, 13, Color(117, 117, 117));
      it.filled_circle(211, 111, 10, Color(117, 117, 117));
      it.filled_circle(229, 104, 13, Color(117, 117, 117));
      it.filled_circle(245, 111, 10, Color(117, 117, 117));
      it.filled_rectangle(212, 106, 33, 16, Color(117, 117, 117));

      it.line(106, 47, 106, 205, Color(255, 255, 255));

# Fonts
font:
  - file: "gfonts://Roboto"
    id: Roboto_14
    size: 14
  - file: "gfonts://Roboto"
    id: Roboto_30
    size: 30
  - file: "gfonts://Roboto"
    id: Roboto
    size: 20